### ISSUE TITLE
Console writer and newlines

### ISSUE THREAD

**Issue by dominik-hadl** [tonystone/tracelog#55]
Should ConsoleWriter output a newline at the end of each log? Or is it intended to work that way?

**Comment by tonystone** [comment]
Hi Nick, it is intended to have a newline at the end.  It looks like we lost that on the ConsoleWriter in the last release when we switched from `print` to `standardOutput.write`.  I'll get that fixed asap and get a point release out.

Thanks for bringing that to our attention.

**Comment by dominik-hadl** [comment]
@tonystone Amazingly fast response and fix. Great (frame)work 👍

**Comment by tonystone** [comment]
@nickskull Tagged it 4.0.1.  Use that version for SPM, or if you are using CocoaPods, I also pushed 4.0.1 to the trunk, so that is all ready for you as well.

Let me know if you have any other issues.  Also, if we're all clear with this one, let me know, and I'll close it out.

**Comment by dominik-hadl** [comment]
All good, thanks again!
